enum Events {
  SET_SCORE = 'SET_SCORE',
  SET_DAMAGE = 'SET_DAMAGE',
  SET_PAUSE = 'SET_PAUSE',
  SET_WIN = 'SET_WIN',
  SET_LOSE = 'SET_LOSE',
  LASER_SHOT = 'LASER_SHOT',
  PLAYER_DAMAGED = 'PLAYER_DAMAGED',
}

export default Events;
