enum GameState {
  GAME = 'PLAY',
  PAUSE = 'PAUSE',
  GAME_OVER_WIN = 'GAME_OVER_WIN',
  GAME_OVER_LOSE = 'GAME_OVER_LOSE',
}

const DEFAULT_HEALTH_COUNT = 3;

const INITIAL_TIME = 60;

export {
  GameState,
  DEFAULT_HEALTH_COUNT,
  INITIAL_TIME,
};
